var classes = [
    {
        "name": "App\\Game",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "setGames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getGames",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\GameRepository"
        ],
        "parents": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 4,
        "volume": 14,
        "difficulty": 2,
        "effort": 28,
        "level": 0.5,
        "bugs": 0,
        "time": 2,
        "intelligentContent": 7,
        "number_operators": 3,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 66.84,
        "mIwoC": 66.84,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 3,
        "package": "App\\",
        "pageRank": 0.11,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\GameRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getPdo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchGames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "insertGames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "PDO",
            "PDO",
            "PDOException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 24,
        "vocabulary": 14,
        "volume": 91.38,
        "difficulty": 4.44,
        "effort": 406.12,
        "level": 0.23,
        "bugs": 0.03,
        "time": 23,
        "intelligentContent": 20.56,
        "number_operators": 8,
        "number_operands": 16,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 11,
        "loc": 36,
        "lloc": 25,
        "mi": 93.14,
        "mIwoC": 55.37,
        "commentWeight": 37.77,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 76.5,
        "package": "App\\",
        "pageRank": 0.39,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsers",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\UserRepository"
        ],
        "parents": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 4,
        "volume": 18,
        "difficulty": 3,
        "effort": 54,
        "level": 0.33,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 6,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 63.69,
        "mIwoC": 63.69,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 1.67,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 5,
        "package": "App\\",
        "pageRank": 0.11,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\UserRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getPdo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchUsers1",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchUsers2",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchUsers3",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "PDO",
            "PDO",
            "PDOException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 30,
        "vocabulary": 16,
        "volume": 120,
        "difficulty": 4.55,
        "effort": 545.45,
        "level": 0.22,
        "bugs": 0.04,
        "time": 30,
        "intelligentContent": 26.4,
        "number_operators": 10,
        "number_operands": 20,
        "number_operators_unique": 5,
        "number_operands_unique": 11,
        "cloc": 20,
        "loc": 53,
        "lloc": 33,
        "mi": 92.63,
        "mIwoC": 51.91,
        "commentWeight": 40.72,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.83,
        "relativeSystemComplexity": 25.83,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 4.17,
        "totalSystemComplexity": 129.17,
        "package": "App\\",
        "pageRank": 0.39,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    }
]