var classes = [
    {
        "name": "App\\GameRepositoryYongHan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getPdo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchGames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addGame",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateGameIsArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateGameHasAllKeys",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateGameMissingKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 11,
        "ccnMethodMax": 8,
        "externals": [
            "PDO",
            "PDO",
            "PDOException"
        ],
        "parents": [],
        "lcom": 4,
        "length": 102,
        "vocabulary": 33,
        "volume": 514.53,
        "difficulty": 8.89,
        "effort": 4573.58,
        "level": 0.11,
        "bugs": 0.17,
        "time": 254,
        "intelligentContent": 57.88,
        "number_operators": 22,
        "number_operands": 80,
        "number_operators_unique": 6,
        "number_operands_unique": 27,
        "cloc": 17,
        "loc": 67,
        "lloc": 50,
        "mi": 77.65,
        "mIwoC": 42.47,
        "commentWeight": 35.18,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.53,
        "relativeSystemComplexity": 26.53,
        "totalStructuralComplexity": 150,
        "totalDataComplexity": 9.17,
        "totalSystemComplexity": 159.17,
        "package": "App\\",
        "pageRank": 0.36,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\GameYongHan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setGames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getGames",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addGameName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\GameRepositoryYongHan"
        ],
        "parents": [],
        "lcom": 2,
        "length": 15,
        "vocabulary": 5,
        "volume": 34.83,
        "difficulty": 3.33,
        "effort": 116.1,
        "level": 0.3,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 10.45,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 22,
        "lloc": 22,
        "mi": 59.79,
        "mIwoC": 59.79,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 9,
        "package": "App\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "RedirectYongHan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "redirect200",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateUserSessionIsEmptyTrue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 2,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 1.67,
        "effort": 30.96,
        "level": 0.6,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 11.15,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 66.68,
        "mIwoC": 66.68,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "App\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\UserRepositoryYongHan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getPdo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loginUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "userRegistration",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchUser1",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchAdmin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateUserIsArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateUserKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateUserMissingKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 11,
        "ccnMethodMax": 6,
        "externals": [
            "PDO",
            "PDO",
            "PDOException"
        ],
        "parents": [],
        "lcom": 4,
        "length": 106,
        "vocabulary": 37,
        "volume": 552.2,
        "difficulty": 9.1,
        "effort": 5025.04,
        "level": 0.11,
        "bugs": 0.18,
        "time": 279,
        "intelligentContent": 60.68,
        "number_operators": 28,
        "number_operands": 78,
        "number_operators_unique": 7,
        "number_operands_unique": 30,
        "cloc": 38,
        "loc": 105,
        "lloc": 69,
        "mi": 79.35,
        "mIwoC": 39.21,
        "commentWeight": 40.14,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.28,
        "relativeSystemComplexity": 27.28,
        "totalStructuralComplexity": 225,
        "totalDataComplexity": 20.5,
        "totalSystemComplexity": 245.5,
        "package": "App\\",
        "pageRank": 0.36,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\UserYongHan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsers",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\UserRepositoryYongHan"
        ],
        "parents": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 4,
        "volume": 18,
        "difficulty": 3,
        "effort": 54,
        "level": 0.33,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 6,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 63.69,
        "mIwoC": 63.69,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 1.67,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 5,
        "package": "App\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]